import { Source } from "./types";

export const sources: Source[] = [
  {
    id: "lequipe",
    name: "L'Équipe",
    url: "https://www.lequipe.fr",
    feedUrl: "https://www.lequipe.fr/rss/actu_rss_Football.xml",
    tier: 1,
    tags: ["Presse Sportive"],
    country: "France",
    countryFlag: "🇫🇷",
    description: "Quotidien sportif français de référence",
  },
  {
    id: "marca",
    name: "Marca",
    url: "https://www.marca.com",
    feedUrl: "https://e00-marca.uecdn.es/rss/futbol/futbol.xml",
    tier: 2,
    tags: ["Presse Sportive", "Pro-Real Madrid"],
    country: "Espagne",
    countryFlag: "🇪🇸",
    description: "Quotidien sportif madrilène, proche du Real Madrid",
  },
  {
    id: "sport",
    name: "Sport",
    url: "https://www.sport.es",
    feedUrl: "https://www.sport.es/es/rss/futbol/rss.xml",
    tier: 2,
    tags: ["Journal Catalan", "Pro-Barça"],
    country: "Espagne",
    countryFlag: "🇪🇸",
    description: "Quotidien sportif catalan, proche du FC Barcelone",
  },
  {
    id: "mundodeportivo",
    name: "Mundo Deportivo",
    url: "https://www.mundodeportivo.com",
    feedUrl: "https://www.mundodeportivo.com/rss/futbol/rss.xml",
    tier: 2,
    tags: ["Journal Catalan", "Pro-Barça"],
    country: "Espagne",
    countryFlag: "🇪🇸",
    description: "Quotidien sportif basé à Barcelone",
  },
  {
    id: "skysports",
    name: "Sky Sports",
    url: "https://www.skysports.com",
    feedUrl: "https://www.skysports.com/rss/12040",
    tier: 1,
    tags: ["Télévision", "Spécialiste Mercato"],
    country: "Angleterre",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    description: "Chaîne sportive britannique, références mercato PL",
  },
  {
    id: "bbc",
    name: "BBC Sport Football",
    url: "https://www.bbc.com/sport/football",
    feedUrl: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    tier: 1,
    tags: ["Presse Sportive"],
    country: "Angleterre",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    description: "Service public britannique, très fiable",
  },
  {
    id: "gazzetta",
    name: "La Gazzetta dello Sport",
    url: "https://www.gazzetta.it",
    feedUrl: "https://www.gazzetta.it/rss/Calcio.xml",
    tier: 2,
    tags: ["Presse Sportive"],
    country: "Italie",
    countryFlag: "🇮🇹",
    description: "Principal quotidien sportif italien",
  },
  {
    id: "kicker",
    name: "Kicker",
    url: "https://www.kicker.de",
    feedUrl: "https://rss.kicker.de/news/aktuell",
    tier: 2,
    tags: ["Presse Sportive"],
    country: "Allemagne",
    countryFlag: "🇩🇪",
    description: "Magazine sportif allemand de référence",
  },
  {
    id: "fabrizio-romano",
    name: "Fabrizio Romano (Mock)",
    url: "https://twitter.com/FabrizioRomano",
    feedUrl: "",
    tier: 1,
    tags: ["Spécialiste Mercato", "Journaliste Indépendant"],
    country: "Italie",
    countryFlag: "🇮🇹",
    description: "Journaliste transferts #1 mondial — Here we go!",
  },
  {
    id: "the-sun",
    name: "The Sun",
    url: "https://www.thesun.co.uk",
    feedUrl: "https://www.thesun.co.uk/sport/football/feed/",
    tier: 4,
    tags: ["Tabloïd"],
    country: "Angleterre",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    description: "Tabloïd britannique, beaucoup de clickbait",
  },
];
