"""Shared demo data for Vercel serverless functions."""
from datetime import datetime, timedelta

NOW = datetime.utcnow()

SOURCES = [
    {"id": "guardian_football", "name": "The Guardian Football", "type": "newspaper",
     "country": "GB", "language": "en", "city": "Londres", "reliability": 5,
     "tags": ["Angleterre", "Qualité"], "affiliation": None, "enabled": True},
    {"id": "bbc_sport", "name": "BBC Sport Football", "type": "newspaper",
     "country": "GB", "language": "en", "city": "Londres", "reliability": 5,
     "tags": ["Angleterre", "Service public"], "affiliation": None, "enabled": True},
    {"id": "lequipe", "name": "L'Équipe", "type": "newspaper",
     "country": "FR", "language": "fr", "city": "Paris", "reliability": 4,
     "tags": ["France", "Généraliste"], "affiliation": None, "enabled": True},
    {"id": "gazzetta", "name": "La Gazzetta dello Sport", "type": "newspaper",
     "country": "IT", "language": "it", "city": "Milan", "reliability": 4,
     "tags": ["Italie", "Généraliste"], "affiliation": None, "enabled": True},
    {"id": "kicker", "name": "Kicker", "type": "newspaper",
     "country": "DE", "language": "de", "city": "Nuremberg", "reliability": 4,
     "tags": ["Allemagne", "Généraliste"], "affiliation": None, "enabled": True},
    {"id": "marca", "name": "Marca", "type": "newspaper",
     "country": "ES", "language": "es", "city": "Madrid", "reliability": 3,
     "tags": ["Espagne", "Madrid"], "affiliation": "Real Madrid", "enabled": True},
    {"id": "as_es", "name": "AS", "type": "newspaper",
     "country": "ES", "language": "es", "city": "Madrid", "reliability": 3,
     "tags": ["Espagne", "Madrid"], "affiliation": "Real Madrid", "enabled": True},
    {"id": "leparisien", "name": "Le Parisien Sport", "type": "newspaper",
     "country": "FR", "language": "fr", "city": "Paris", "reliability": 3,
     "tags": ["France", "Paris"], "affiliation": "PSG", "enabled": True},
    {"id": "sky_sports", "name": "Sky Sports Football", "type": "newspaper",
     "country": "GB", "language": "en", "city": "Londres", "reliability": 3,
     "tags": ["Angleterre"], "affiliation": None, "enabled": True},
    {"id": "corriere_sport", "name": "Corriere dello Sport", "type": "newspaper",
     "country": "IT", "language": "it", "city": "Rome", "reliability": 3,
     "tags": ["Italie", "Rome"], "affiliation": None, "enabled": True},
    {"id": "sport_es", "name": "Sport", "type": "newspaper",
     "country": "ES", "language": "es", "city": "Barcelone", "reliability": 2,
     "tags": ["Espagne", "Barcelone"], "affiliation": "FC Barcelone", "enabled": True},
    {"id": "mundodeportivo", "name": "Mundo Deportivo", "type": "newspaper",
     "country": "ES", "language": "es", "city": "Barcelone", "reliability": 2,
     "tags": ["Espagne", "Barcelone"], "affiliation": "FC Barcelone", "enabled": True},
    {"id": "tuttosport", "name": "Tuttosport", "type": "newspaper",
     "country": "IT", "language": "it", "city": "Turin", "reliability": 2,
     "tags": ["Italie", "Turin"], "affiliation": "Juventus", "enabled": True},
    {"id": "bild", "name": "Bild Sport", "type": "newspaper",
     "country": "DE", "language": "de", "city": "Berlin", "reliability": 2,
     "tags": ["Allemagne", "Tabloïd"], "affiliation": None, "enabled": True},
    {"id": "fabrizio_romano", "name": "Fabrizio Romano", "type": "journalist",
     "country": "IT", "language": "en", "city": "Londres", "reliability": 5,
     "tags": ["Mercato", "Here we go"], "affiliation": None, "enabled": True},
    {"id": "david_ornstein", "name": "David Ornstein", "type": "journalist",
     "country": "GB", "language": "en", "city": "Londres", "reliability": 5,
     "tags": ["Mercato", "Premier League", "The Athletic"], "affiliation": None, "enabled": True},
    {"id": "matteo_moretto", "name": "Matteo Moretto", "type": "journalist",
     "country": "IT", "language": "es", "city": "Barcelone", "reliability": 4,
     "tags": ["Mercato", "Liga", "Serie A"], "affiliation": None, "enabled": True},
    {"id": "romain_molina", "name": "Romain Molina", "type": "journalist",
     "country": "FR", "language": "fr", "city": "Paris", "reliability": 4,
     "tags": ["Investigation", "Coulisses"], "affiliation": None, "enabled": True},
    {"id": "ekrem_konur", "name": "Ekrem Konur", "type": "journalist",
     "country": "TR", "language": "en", "city": "Istanbul", "reliability": 2,
     "tags": ["Mercato", "Turquie"], "affiliation": None, "enabled": True},
    {"id": "le10sport", "name": "Le10Sport", "type": "website",
     "country": "FR", "language": "fr", "city": "Paris", "reliability": 2,
     "tags": ["France", "Mercato", "Putaclick"], "affiliation": None, "enabled": True},
    {"id": "footmercato", "name": "Foot Mercato", "type": "website",
     "country": "FR", "language": "fr", "city": "Paris", "reliability": 2,
     "tags": ["France", "Mercato"], "affiliation": None, "enabled": True},
]

SOURCE_MAP = {s["id"]: s for s in SOURCES}


def _art(idx, source_id, title, summary, hours_ago, cb_score, cb_flags, url=None):
    src = SOURCE_MAP[source_id]
    rel = src["reliability"]
    final = max(1.0, min(5.0, rel - cb_score * 2))
    return {
        "id": f"demo_{idx:03d}",
        "title": title,
        "url": url or f"https://example.com/article-{idx}",
        "summary": summary,
        "published_at": (NOW - timedelta(hours=hours_ago)).isoformat(),
        "author": None,
        "image_url": None,
        "source": {
            "id": src["id"], "name": src["name"], "type": src["type"],
            "country": src["country"], "city": src["city"],
            "reliability": rel, "tags": src["tags"], "affiliation": src["affiliation"],
        },
        "scores": {
            "source_reliability": rel,
            "clickbait_score": cb_score,
            "final_score": round(final, 2),
            "clickbait_flags": cb_flags,
        },
    }


ARTICLES = [
    _art(0,  "guardian_football",
         "Arsenal confirm £65m signing of midfielder on five-year deal",
         "The Gunners have ended their pursuit of the player with an official announcement.",
         0.5, 0.0, []),
    _art(1,  "bbc_sport",
         "Liverpool 3-1 Newcastle: Salah double seals comfortable win",
         "Mohamed Salah scored twice as Liverpool moved to the top of the Premier League table.",
         1.0, 0.0, []),
    _art(2,  "guardian_football",
         "Manchester City injury crisis deepens ahead of Champions League tie",
         "Pep Guardiola confirmed three key players will miss Tuesday's first leg.",
         1.5, 0.0, []),
    _art(3,  "bbc_sport",
         "Euro 2026 qualifying: France qualify after goalless draw with Belgium",
         "France secured their place at Euro 2026 despite being held at the Stade Roi Baudouin.",
         2.0, 0.0, []),
    _art(4,  "lequipe",
         "PSG : Luis Enrique satisfait de la réaction de son équipe après le nul",
         "Le technicien espagnol a salué l'état d'esprit de ses joueurs en conférence de presse.",
         2.5, 0.0, []),
    _art(5,  "fabrizio_romano",
         "HERE WE GO! Confirmed deal done — attacking midfielder joins Premier League club on permanent basis",
         "Medical completed ✅ Contracts signed. Official announcement expected within hours.",
         0.2, 0.05, []),
    _art(6,  "david_ornstein",
         "EXCLUSIVE: Premier League manager set to leave club by mutual consent today",
         "Board meeting scheduled for this afternoon. A statement expected before matchday.",
         3.0, 0.05, []),
    _art(7,  "kicker",
         "Bayern München verlängert Vertrag mit Torhüter bis 2027",
         "Der deutsche Rekordmeister setzt weiter auf seinen Stammtorhüter Manuel Neuer.",
         3.5, 0.0, []),
    _art(8,  "gazzetta",
         "Inter Milan: Lautaro Martinez verso il rinnovo fino al 2028",
         "Il capitano nerazzurro è pronto a firmare il nuovo contratto con aumento importante.",
         4.0, 0.0, []),
    _art(9,  "lequipe",
         "Équipe de France : Deschamps convoque une liste remaniée avec deux nouveaux visages",
         "Le sélectionneur a surpris en appelant deux joueurs de Ligue 1 pour les prochains matchs.",
         4.5, 0.0, []),
    _art(10, "matteo_moretto",
         "Exclusiva: el FC Barcelona negocia la renovación de su central antes del mercado de verano",
         "Las conversaciones avanzan bien según fuentes cercanas al club.",
         5.0, 0.10, ["Source vague"]),
    _art(11, "romain_molina",
         "Enquête : les dérives financières d'un club de Ligue 1 mises au jour",
         "Plusieurs irrégularités comptables relevées lors d'un audit interne confidentiel.",
         5.5, 0.0, []),
    _art(12, "sky_sports",
         "Chelsea make £80m bid for Champions League winner",
         "The Blues are keen to bolster their attacking options before the summer window closes.",
         6.0, 0.10, ["Source vague"]),
    _art(13, "marca",
         "Real Madrid : Vinicius Junior prolonge son contrat jusqu'en 2030 !",
         "Le Brésilien a signé un nouveau contrat record au Santiago Bernabéu ce mardi.",
         6.5, 0.05, []),
    _art(14, "corriere_sport",
         "Napoli-Inter: la sfida scudetto si decide al Maradona",
         "Partita ad alta tensione nella corsa al titolo. Conte contro Inzaghi.",
         7.0, 0.0, []),
    _art(15, "as_es",
         "EXCLUSIVA: según nuestras fuentes, el Real Madrid quiere un gran defensa este verano !!!",
         "Un club inglés estaría también en la puja según informaciones de nuestros insiders.",
         7.5, 0.50, ["Source vague", "Ponctuation excessive", "Urgence artificielle"]),
    _art(16, "sport_es",
         "IMMINENT : le Barça aurait un accord verbal avec une star !!!",
         "Selon des sources proches du dossier, le deal serait pratiquement bouclé…",
         8.0, 0.75, ["Urgence artificielle", "Source vague", "Ponctuation excessive"]),
    _art(17, "tuttosport",
         "INCROYABLE : la Juve prête à tout pour signer une star mondiale cet été ?!?",
         "Selon nos informations, un grand club anglais serait prêt à surenchérir sur l'offre.",
         8.5, 0.80, ["Sensationnalisme", "Source vague", "Sujet volontairement vague", "Ponctuation excessive"]),
    _art(18, "le10sport",
         "BREAKING !!! Vous ne croirez pas qui veut signer un joueur du PSG !!!",
         "Un club européen serait prêt à formuler une offre massive selon nos sources exclusives...",
         9.0, 0.95, ["Appât au clic", "Source vague", "Urgence artificielle", "Ponctuation excessive"]),
    _art(19, "footmercato",
         "Mercato : une star mondiale pourrait débarquer à Paris selon nos sources",
         "L'information serait imminente selon des insiders très proches du dossier...",
         9.5, 0.85, ["Source vague", "Conditionnel spéculatif", "Urgence artificielle"]),
    _art(20, "bild",
         "HAMMER-TRANSFER !!! BVB holt Weltklasse-Stürmer für 90 Millionen ???",
         "Laut unseren Quellen soll der Deal kurz vor dem Abschluss stehen.",
         10.0, 0.80, ["Sensationnalisme", "Source vague", "Ponctuation excessive"]),
    _art(21, "ekrem_konur",
         "BREAKING: Top European club closes in on signing of Turkish international striker",
         "A big club could be ready to submit a massive bid according to insider sources.",
         10.5, 0.70, ["Source vague", "Urgence artificielle", "Conditionnel spéculatif"]),
    _art(22, "leparisien",
         "PSG – Mercato : un attaquant de renom dans le viseur du club parisien cet été",
         "La direction parisienne chercherait à renforcer son secteur offensif selon nos informations.",
         11.0, 0.30, ["Source vague", "Conditionnel spéculatif"]),
    _art(23, "mundodeportivo",
         "El Barça podría fichar a un delantero top según fuentes del club",
         "Reunión esta semana entre los representantes y la dirección deportiva culé.",
         11.5, 0.45, ["Source vague", "Conditionnel spéculatif"]),
    _art(24, "guardian_football",
         "Women's Super League: Arsenal reclaim top spot with commanding victory",
         "Vivianne Miedema starred as Arsenal moved clear at the summit of the WSL.",
         12.0, 0.0, []),
]
